### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#122]
Came across a couple of unhandled exceptions when running the storage receiver. The signer does happen to be the same but that's not necessarily connected as the second one had already been written out successfully.

```
2020-02-25 15:30:51,269 - ssm.ssm2 - INFO - Received message. ID = 5e521198/5e5211aacb00bb
2020-02-25 15:30:51,269 - ssm.crypto - INFO - Decrypting message.
2020-02-25 15:30:51,747 - ssm.ssm2 - INFO - Valid signer: XXXXXX
2020-02-25 15:30:51,751 - ssm.ssm2 - INFO - Message saved to incoming queue as 000103c1/5e553dabb78432
2020-02-25 15:30:51,772 - ssm.ssm2 - INFO - Received message. ID = 5e521198/5e5211ab128cfb
2020-02-25 15:30:51,773 - ssm.crypto - INFO - Decrypting message.
2020-02-25 15:30:51,915 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 741, in __receiver_loop
    self.__notify(frame_type, headers, body)
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 718, in __notify
    notify_func(headers, body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 230, in on_message
    extracted_msg, signer, err_msg = self._handle_msg(body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 331, in _handle_msg
    message, signer = crypto.verify(text, self._capath, self._check_crls)
  File "/usr/lib/python2.7/site-packages/ssm/crypto.py", line 148, in verify
    signer = get_signer_cert(signed_text)
  File "/usr/lib/python2.7/site-packages/ssm/crypto.py", line 327, in get_signer_cert
    p1.stdin.write(signed_text)
IOError: [Errno 32] Broken pipe
2020-02-25 15:34:57,812 - ssmreceive - INFO - Received the shutdown signal: Terminating on signal 15
2020-02-25 15:34:57,813 - ssm.ssm2 - INFO - SSM connection ended.
2020-02-25 15:34:57,813 - ssmreceive - INFO - Receiving SSM has shut down.
2020-02-25 15:34:57,813 - ssmreceive - INFO - ========================================
```

```
2020-02-25 15:38:35,433 - ssm.ssm2 - INFO - Received message. ID = 5e536318/5e5363296c454a
2020-02-25 15:38:35,433 - ssm.crypto - INFO - Decrypting message.
2020-02-25 15:38:35,641 - ssm.ssm2 - INFO - Valid signer: XXXXXX
2020-02-25 15:38:35,646 - ssm.ssm2 - INFO - Message saved to incoming queue as 000103c2/5e553f7b9dda50
2020-02-25 15:38:35,875 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 737, in __receiver_loop
    (frame_type, headers, body) = utils.parse_frame(frame)
  File "/usr/lib/python2.7/site-packages/stomp/utils.py", line 48, in parse_frame
    frame_type = preamble_lines[first_line]
IndexError: list index out of range
2020-02-25 15:39:38,885 - ssmreceive - INFO - Received the shutdown signal: Terminating on signal 15
2020-02-25 15:39:38,886 - ssm.ssm2 - INFO - SSM connection ended.
2020-02-25 15:39:38,886 - ssmreceive - INFO - Receiving SSM has shut down.
```

**Comment by tofu-rocketry** [comment]
Some others.

This one is super common at the moment (since around the 7th Sept 2020 - poss AMS change):

```
2020-09-17 16:24:06,451 - ssmreceive - ERROR - Unexpected exception: {'status_code': 408, 'error': "While trying the [sub_pull]: <html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"}
2020-09-17 16:24:06,451 - ssmreceive - ERROR - Exception type: <class 'argo_ams_library.amsexceptions.AmsServiceException'>
2020-09-17 16:24:06,451 - ssmreceive - ERROR - The SSM will exit.
2020-09-17 16:24:06,451 - ssmreceive - INFO - Receiving SSM has shut down.
2020-09-17 16:24:06,451 - ssmreceive - INFO - ========================================
```

```
2020-09-17 16:34:32,996 - ssmreceive - ERROR - Unexpected exception: [Errno 104] Connection reset by peer
2020-09-17 16:34:32,996 - ssmreceive - ERROR - Exception type: <class 'socket.error'>
2020-09-17 16:34:32,996 - ssmreceive - ERROR - The SSM will exit.
2020-09-17 16:34:32,996 - ssmreceive - INFO - Receiving SSM has shut down.
2020-09-17 16:34:32,996 - ssmreceive - INFO - ========================================
```

**Comment by tofu-rocketry** [comment]
This is the other `AmsServiceException `you sometimes get:

```
2020-09-08 09:02:57,845 - ssmreceive - ERROR - Unexpected exception: {'status_code': 504, 'error': "While trying the [sub_pull]: <html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"}
2020-09-08 09:02:57,845 - ssmreceive - ERROR - Exception type: <class 'argo_ams_library.amsexceptions.AmsServiceException'>
2020-09-08 09:02:57,845 - ssmreceive - ERROR - The SSM will exit.
2020-09-08 09:02:57,845 - ssmreceive - INFO - Receiving SSM has shut down.
2020-09-08 09:02:57,845 - ssmreceive - INFO - ========================================
```

**Comment by tofu-rocketry** [comment]
The `AmsServiceException`s should be solved by newer versions of the AMS library (>=0.5.1).

The [README.md](https://github.com/ARGOeu/argo-ams-library/tree/devel#retry) says retries will be performed for the following:

>    - timeouts from AMS (HTTP 408) or load balancer (HTTP 408 and 504)
>    - load balancer HTTP 502, 503
>    - connection related problems in the lower network layers

**Comment by tofu-rocketry** [comment]
There doesn't seem to have been unhandled exceptions for a very long time with the new versions of the AMS library.
