### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by zinus92** [apel/ssm#257]
Hi, I'm trying the new release 3.3.0-1 in container mode, but, when the ssmsend command is launched, I obtain

`# ssmsend
Traceback (most recent call last):
  File "/usr/bin/ssmsend", line 5, in <module>
    pkg_resources.run_script('apel-ssm==3.3.0', 'ssmsend')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/apel_ssm-3.3.0-py2.7.egg/EGG-INFO/scripts/ssmsend", line 21, in <module>
    import ssm.agents
  File "/usr/lib/python2.7/site-packages/apel_ssm-3.3.0-py2.7.egg/ssm/agents.py", line 40, in <module>
    from argo_ams_library import (AmsConnectionException, AmsTimeoutException,
  File "/usr/lib/python2.7/site-packages/argo_ams_library/__init__.py", line 11, in <module>
    from .ams import ArgoMessagingService
  File "/usr/lib/python2.7/site-packages/argo_ams_library/ams.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/requests/certs.py", line 15, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax`

Moreover, there are a couple of typo regarding the receiver container command
![image](https://github.com/apel/ssm/assets/67749829/b236b520-b1be-443c-bedc-22ccdab8ceec)

Thanks a lot!

**Comment by gregcorbett** [comment]
I can replicate the "SyntaxError: invalid syntax" - it seems to be caused by the `certifi` package and I'm investigating where this needed to be pinned to maintain SL7 compatibility.

> Moreover, there are a couple of typo regarding the receiver container command

Could you be more specific?

**Comment by gregcorbett** [comment]
I believe this is a Python 2.7 compatibility issue with `certifi`, which I can replicate by installing the `argo-ams-library` via `pip` and trying to import it within Python.

```
> pip install argo-ams-library
> python
>>> import argo_ams_library
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/argo_ams_library/__init__.py", line 11, in <module>
    from .ams import ArgoMessagingService
  File "/usr/lib/python2.7/site-packages/argo_ams_library/ams.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/requests/certs.py", line 15, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax
```

argo-ams-library already pin requests to maintain Python 2.7 compatibility: https://github.com/ARGOeu/argo-ams-library/issues/136, but this doesn't set a minimum version for `certifi`: https://github.com/psf/requests/blob/v2.20.0/setup.py#L48.

I'll experiment with setting a maximum version.

**Comment by gregcorbett** [comment]
I've built a version of the [container in my fork](https://github.com/gregcorbett/ssm/pkgs/container/ssm/128952927?tag=pin-certifi) with `certifi` capped below 2020.4.5.2 - which is the version that dropped support for Python 2.7.

The pull request is here: #264

**Comment by zinus92** [comment]
Thanks for the support. As for typos, the correct command should be as follows, right? I wrote the corrections in CAPITALS.
`
docker run \
    -d --entrypoint ssmreceive \
    -v /path/to/downloaded/config/RECEIVER.cfg:/etc/apel/RECEIVER.cfg \
    -v /path/to/read/messages:/var/spool/apel/INCOMING \
    -v /path/to/dns/file:/etc/apel/dns \
    -v /etc/grid-security:/etc/grid-security \
    -v /path/to/persistently/log:/var/log/apel \
    ghcr.io/apel/ssm
`

**Comment by gregcorbett** [comment]
Ah thanks for that, I've opened #266 - which I believe corrects the docs.
