### ISSUE TITLE
Issue with EL8 rpms which got generated via FPM.

### ISSUE THREAD

**Issue by Sae126V** [apel/ssm#329]
Traceback (most recent call last):
  File "ssmreceive", line 21, in <module>
    import ssm.agents
  File "/usr/lib/python3.6/site-packages/ssm/agents.py", line 50, in <module>
    from ssm.ssm2 import Ssm2, Ssm2Exception
  File "/usr/lib/python3.6/site-packages/ssm/ssm2.py", line 20, in <module>
    from ssm import crypto
  File "/usr/lib/python3.6/site-packages/ssm/crypto.py", line 27, in <module>
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'
[root@host-172-16-103-151 bin]# pip3 install openssl

**Comment by tofu-rocketry** [comment]
Missing pyopenssl rpm dependency:

e.g.

```        FPM_PYTHON="--depends python3 \
        --depends python3-stomppy \
        --depends python3-pip \
        --depends python3-ldap \
        --depends openssl \
        --depends openssl-devel "```
