### ISSUE TITLE
Unhandled exceptions lead to lost messages

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#62]
If an unhandled exception is raised when receiving a message, there is nothing that will catch and log the message that caused this.

**Examples**

Grid:
```
2018-04-29 05:43:24,811 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 741, in __receiver_loop
    self.__notify(frame_type, headers, body)
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 718, in __notify
    notify_func(headers, body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 172, in on_message
    'empaid': empaid})
  File "/usr/lib/python2.7/site-packages/dirq/queue.py", line 938, in add
    _file_write('%s/%s' % (temp, name), 1, self.umask, data[name])
  File "/usr/lib/python2.7/site-packages/dirq/QueueBase.py", line 210, in _file_write
    fileh = _file_create(path, umask=umask, utf8=utf8)
  File "/usr/lib/python2.7/site-packages/dirq/QueueBase.py", line 193, in _file_create
    fileh = codecs.open(path, 'w', 'utf8')
  File "/usr/lib64/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/apel/messages/grid/incoming/temporary/5ae55b7cc5a3f7/body'
```
Storage:
```
2018-05-06 05:41:15,560 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 741, in __receiver_loop
    self.__notify(frame_type, headers, body)
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 718, in __notify
    notify_func(headers, body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 152, in on_message
    raw_msg, signer, err_msg = self._handle_msg(body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 237, in _handle_msg
    message, signer = crypto.verify(text, self._capath, self._check_crls)
  File "/usr/lib/python2.7/site-packages/ssm/crypto.py", line 163, in verify
    blankline = lines.index('')
ValueError: '' is not in list
```
Cloud:
```
2018-04-13 22:30:12,197 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 741, in __receiver_loop
    self.__notify(frame_type, headers, body)
  File "/usr/lib/python2.7/site-packages/stomp/connect.py", line 718, in __notify
    notify_func(headers, body)
  File "/usr/lib/python2.7/site-packages/ssm/ssm2.py", line 172, in on_message
    'empaid': empaid})
  File "/usr/lib/python2.7/site-packages/dirq/queue.py", line 938, in add
    _file_write('%s/%s' % (temp, name), 1, self.umask, data[name])
  File "/usr/lib/python2.7/site-packages/dirq/QueueBase.py", line 215, in _file_write
    raise IOError("cannot write to %s: %s" % (path, error))
IOError: cannot write to /apel/messages/cloud/incoming/temporary/5ad12f742db45a/body: 'ascii' codec can't decode byte 0xe2 in position 2082281: ordinal not in range(128)
```

**Comment by tofu-rocketry** [comment]
First one is a case of `IOError` not being caught, even though there's no real difference to OSError, which is caught in `on_message`: https://www.python.org/dev/peps/pep-3151/#confusing-set-of-os-related-exceptions

**Comment by tofu-rocketry** [comment]
Second one seems to be due to a mostly valid message not having a blank line in it, which is usually expected between the header and message.
